### ISSUE TITLE
I hope to receive your assistance.

### ISSUE THREAD

**Issue by Suonudo** [TesfayZ/CCM_MADRL_MEC#11]
Dear Author,  

I hope this message finds you well. I recently ran your code using PyCharm and, following the instructions in the README file, modified `sys.argv[1]` to `[0]` in the `run.py` file located in the `CCM_MADRL_MEC-master` folder. However, I encountered an error during execution and am unsure how to proceed with resolving it.  

I would be very grateful if you could provide some guidance or advice to help me address this issue.  

Thank you in advance for your time and assistance.  

Best regards

Here is the error message：
D:\Anacoda\python.exe E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\run.py 
Traceback (most recent call last):
  File "E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\run.py", line 41, in <module>
    run(InfdexofResult) 
  File "E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\run.py", line 36, in run
    ddpg = [create_ddpg(InfdexofResult, env, eval_env, EPISODES_BEFORE_TRAIN, MAX_EPISODES)]
  File "E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\run.py", line 18, in create_ddpg
    ccmaddpg.interact(MAX_EPISODES, EPISODES_BEFORE_TRAIN, NUMBER_OF_EVAL_EPISODES)
  File "E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\CCM_MADRL.py", line 103, in interact
    self.evaluate(NUMBER_OF_EVAL_EPISODES) 
  File "E:\CCM_MADRL_MEC-master\CCM_MADRL_MEC-master\s10lre4e3CCM_MADRL_MEC\CCM_MADRL.py", line 525, in evaluate
    savetxt('./CSV/results/CCM_MADRL'+str(self.InfdexofResult)+'.csv', arrayresults)
  File "<__array_function__ internals>", line 180, in savetxt
  File "D:\Anacoda\lib\site-packages\numpy\lib\npyio.py", line 1523, in savetxt
    open(fname, 'wt').close()
OSError: [Errno 22] Invalid argument: './CSV/results/CCM_MADRLE:\\CCM_MADRL_MEC-master\\CCM_MADRL_MEC-master\\s10lre4e3CCM_MADRL_MEC\\run.py.csv'

进程已结束,退出代码1
<img width="1013" alt="Snipaste_2024-12-13_04-11-30" src="https://github.com/user-attachments/assets/967ffdeb-c31c-4534-806e-ef755ea70e25" />

**Comment by Suonudo** [comment]
if I ram sys.argv[1],the error message is:IndexError: list index out of range

**Comment by RainPetrichor** [comment]
Hello, I met the same problem, have you solved it? I have a feeling there might be a numpy version issue

**Comment by TesfayZ** [comment]
Hello all,

Goto line 40 of infdexofResult and set it to 0.

I.e. infdexofResult = 0 # comment the rest. Because the infdexofResult
holds a distinguisher integer for the filenames in the csv file. If you
want to run a second a second experiment, do so as infdexofResult = 1,
replacing 0 by 1. If you want run 10 experiments, continue replacing it
upto 9.

How a code is run in miniconda and pycharm us different. In miniconda, it
is run as python run.py 0 to run the first experiment. That's why
infdexofRedult is = arg[1], which means the decond argument. In arg[0] is
the file name, run.py.

I pycharm, you don't run the code fron a comman line. It is run directly
from the file by pressing the run button or F12 I think. This is the
difference.
